<?php

namespace AppBundle\Repository;

/**
 * ProductCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
