<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQcn9tls\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQcn9tls/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQcn9tls.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQcn9tls\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQcn9tls\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Qcn9tls',
    'container.build_id' => '6a12bae3',
    'container.build_time' => 1524992987,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQcn9tls');
